# fly.toml app configuration file generated for servo-app on 2023-09-27T11:41:51+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "servo-app"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
